### ISSUE TITLE
FR: Text Formatting Options - Syntax Highlighting

### ISSUE THREAD

**Issue by richhayler** [craftcms/simple-text#3]
Personally I use this field type plugin extensively across a number of Craft sites. It would be awesome if it supported basic syntax highlighting and provided a dropdown of text formatting options, e.g. HTML, CSS, Twig, Markdown, etc leveraging Prism JS.

Example using behave.js: https://orbitbot.github.io/misbehave/prismjs.html

While there is another good plugin “CodeMirror” that provides this (and a bunch more options), development has since been abandoned and it doesn’t support a number of useful features within Craft, for example “Live Preview”.

I need this so badly I am willing to fund the enhancement for the benefit of the community that uses this.

**Comment by brandonkelly** [comment]
This would be out of scope for this plugin.
